
function GetScripts() return { 	
	"scripts/global.lua",
	"scripts/emitters.lua",
	"scripts/text_weapons.lua",
	"scripts/text_achievements.lua",
	"scripts/text_tooltips.lua",
	"scripts/text_missions.lua",
	"scripts/text_pawns.lua",
	"scripts/text_population.lua",
	"scripts/text.lua",
	"scripts/color_map.lua",
	"scripts/animations.lua",
	"scripts/images.lua",
	"scripts/fonts.lua",
	"scripts/game.lua",
	"scripts/quests.lua",
	"scripts/rumble.lua",
	
	"scripts/weapons_base.lua",
	"scripts/weapons_enemy.lua",
	
	"scripts/weapons_prime.lua",
	"scripts/weapons_ranged.lua",
	"scripts/weapons_brute.lua",
	"scripts/weapons_science.lua",
	"scripts/weapons_deploy.lua",
	"scripts/weapons_support.lua",
	"scripts/weapons_snow.lua",
	"scripts/weapons_passive.lua",
	"scripts/weapons_technovek.lua",
		
	"scripts/personalities/ftcsv.lua",
	"scripts/personalities/personalities.lua",
	"scripts/personalities/dialogs.lua",
	"scripts/corporations.lua",
	
	"scripts/pawns.lua",
	"scripts/squad.lua",
	"scripts/events.lua",
	"scripts/missions/missions.lua",
	"scripts/pilots.lua",
	"scripts/islands.lua",
	"scripts/drops.lua",
	"scripts/spawner_backend.lua",
	"scripts/spawner.lua",
		
	"scripts/structures.lua",
	
	"scripts/environments.lua",
	"scripts/items.lua",
	
	"scripts/missions/mission_critical.lua",
	"scripts/missions/mission_train.lua",
	"scripts/missions/mission_volatile.lua",
	"scripts/missions/mission_minebase.lua",
	"scripts/missions/mission_tutorial.lua",
	
	"scripts/missions/acid/mission_belt.lua",
	"scripts/missions/acid/mission_barrels.lua",
	"scripts/missions/acid/mission_acid.lua",
	"scripts/missions/acid/mission_piston.lua",
	"scripts/missions/acid/mission_laser.lua",
	"scripts/missions/acid/mission_fence.lua",
	"scripts/missions/acid/mission_teleport.lua",
	"scripts/missions/acid/mission_disposal.lua",
	"scripts/missions/acid/mission_acidtank.lua",
	"scripts/missions/acid/mission_respawn.lua",
	
	"scripts/missions/sand/mission_holes.lua",
	"scripts/missions/sand/mission_lightning.lua",
	"scripts/missions/sand/mission_force.lua",
	"scripts/missions/sand/mission_terraform.lua",
	"scripts/missions/sand/mission_sandstorm.lua",
	"scripts/missions/sand/mission_crack.lua",
	"scripts/missions/sand/mission_cataclysm.lua",
	"scripts/missions/sand/mission_filler.lua",
	"scripts/missions/sand/mission_bomb.lua",
	
	"scripts/missions/snow/snow_helper.lua",
	"scripts/missions/snow/mission_snowbattle.lua",
	"scripts/missions/snow/mission_factory.lua",
	"scripts/missions/snow/mission_stasis.lua",
	"scripts/missions/snow/mission_reactivation.lua",
	"scripts/missions/snow/mission_botdefense.lua",
	"scripts/missions/snow/mission_freezemines.lua",
	"scripts/missions/snow/mission_freezebldg.lua",
	"scripts/missions/snow/mission_freezebots.lua",
	"scripts/missions/snow/mission_snowstorm.lua",
	
	"scripts/missions/grass/mission_satellites.lua",
	"scripts/missions/grass/mission_artillery.lua",
	"scripts/missions/grass/mission_airstrike.lua",
	"scripts/missions/grass/mission_tanks.lua",
	"scripts/missions/grass/mission_mines.lua",
	"scripts/missions/grass/mission_dam.lua",
	"scripts/missions/grass/mission_tides.lua",
	
	"scripts/missions/bosses/boss.lua",
	"scripts/missions/bosses/spider.lua",
	"scripts/missions/bosses/bot.lua",
	"scripts/missions/bosses/goo.lua",
	"scripts/missions/bosses/firefly.lua",
	"scripts/missions/bosses/beetle.lua",
	"scripts/missions/bosses/hornet.lua",
	"scripts/missions/bosses/scorpion.lua",
	"scripts/missions/bosses/slug.lua",
	"scripts/missions/bosses/psion.lua",
	
	"scripts/missions/final/env_volcano.lua",
	"scripts/missions/final/mission_final.lua",
	"scripts/missions/final/env_final.lua",
	"scripts/missions/final/mission_final_two.lua",
			
	"scripts/advanced/ae_global.lua",
	"scripts/advanced/ae_images.lua",
	"scripts/advanced/ae_animations.lua",
	"scripts/advanced/ae_game.lua",
	"scripts/advanced/ae_weapons_base.lua",
	"scripts/advanced/ae_weapons_enemy.lua",
	"scripts/advanced/ae_weapons.lua",
	"scripts/advanced/ae_spawner_backend.lua",
	"scripts/advanced/ae_corporations.lua",
	"scripts/advanced/ae_pawns.lua",
	"scripts/advanced/ae_text.lua",
	
	"scripts/advanced/bosses/starfish.lua",
	"scripts/advanced/bosses/burnbug.lua",
	"scripts/advanced/bosses/centipede.lua",
	"scripts/advanced/bosses/digger.lua",
	"scripts/advanced/bosses/scarab.lua",
	"scripts/advanced/bosses/blobber.lua",
	"scripts/advanced/bosses/leaper.lua",
	"scripts/advanced/bosses/crab.lua",
	"scripts/advanced/bosses/dung.lua",
	"scripts/advanced/bosses/bouncer.lua",
	"scripts/advanced/bosses/shaman.lua",
	"scripts/advanced/bosses/mosquito.lua",
		
	"scripts/advanced/missions/grass/mission_armored_train.lua",
	"scripts/advanced/missions/grass/mission_fires.lua",
	"scripts/advanced/missions/grass/mission_repair.lua",
	"scripts/advanced/missions/sand/mission_trapped.lua",
	"scripts/advanced/missions/sand/mission_wind.lua",
	"scripts/advanced/missions/sand/mission_terratide.lua",
	"scripts/advanced/missions/snow/mission_boombots.lua",
	"scripts/advanced/missions/snow/mission_hacking.lua",
	"scripts/advanced/missions/snow/mission_shields.lua",
	"scripts/advanced/missions/acid/mission_civilians.lua",
	"scripts/advanced/missions/acid/mission_acidstorm.lua",
	"scripts/advanced/missions/acid/mission_nanostorm.lua",
	"scripts/advanced/missions/acid/mission_missiles.lua",
	
	"scripts/advanced/ae_pilots.lua",
	
	--"scripts/missions/mission_ae_trailer.lua",--TRAILER

	"user/missionData.lua",

	"scripts/mod_loader/__scripts.lua"
}
end